#!/usr/bin/env python3
"""Script for generating joystick scaling tables.

 --Jacques Gagnon <darthcloud@gmail.com>
"""

import os
from js_scale import get_joysticks, get_gc_js_scale_tables

if __name__ == "__main__":
    scale_tables = get_gc_js_scale_tables(get_joysticks())

    tableasm = "../firmware/js_scale.inc"

    if os.path.exists(tableasm):
        os.unlink(tableasm)

    FILE = open(tableasm, "wb")

    FILE.write(b"    ;; 256 bytes tables for scaling GC joysticks.\n")
    FILE.write(b"    ;; Generated by Jacques Gagnon <darthcloud@gmail.com>.\n")
    FILE.write(b"    ;; See notes/gen_asm_js_scale.py\n")
    FILE.write(b"\n")
    FILE.write(b"gamecube_js_scale\n")
    FILE.write(b"    db  ")

    for byte in range(256):
        FILE.write(b"0x%02X" % (scale_tables[0][byte]))
        if byte != 255:
            FILE.write(b", ")

    FILE.write(b"\n")
    FILE.write(b"gamecube_cs_scale\n")
    FILE.write(b"    db  ")

    for byte in range(256):
        FILE.write(b"0x%02X" % (scale_tables[1][byte]))
        if byte != 255:
            FILE.write(b", ")

    FILE.write(b"\n\n")
    FILE.close()

    print("{} generated.".format(tableasm))

### The End ###
