#!/usr/bin/env python2
#
# This script generate the file 'large_table_crc.inc' to be included
# in the firmware. It pack on the MCU flash two bytes per word to be
# read by the TBLRD instruction.
#
# --Jacques Gagnon <darthcloud@gmail.com>
#

import cPickle, os
from crc import extractTable, verifyAlgorithm, reversedLargeTableCRC

if __name__ == "__main__":
    testVectors = cPickle.load(open("crc_test_vectors.p", "rb"))

    tableasm = "../firmware/large_table_crc.inc"

    table = list(reversed(extractTable(testVectors)))
    verifyAlgorithm(testVectors, reversedLargeTableCRC, table)

    if os.path.exists(tableasm):
        os.unlink(tableasm)

    FILE = open(tableasm,"wb")

    FILE.write("    ;; Large 256 byte table for CRC calculation.\n")
    FILE.write("    ;; Generated by Jacques Gagnon <darthcloud@gmail.com>.\n")
    FILE.write("    ;; See notes/gen_asm_large_table_crc.py\n")
    FILE.write("\n")
    FILE.write("    db  ")

    for byte in xrange(256):
        FILE.write("0x%02X" % (table[byte]))
        if byte != 255:
            FILE.write(", ")

    FILE.write("\n")
    FILE.close()

    print "%s generated." % tableasm

### The End ###
